# Claude Code MR Review for GitLab CI
#
# Setup:
# 1. Copy this file to your repo or include it in .gitlab-ci.yml
# 2. Add ANTHROPIC_API_KEY to your CI/CD variables (Settings > CI/CD > Variables)
# 3. Add GITLAB_TOKEN with api scope for posting comments
# 4. MRs will automatically get AI reviews as comments
#
# Usage in .gitlab-ci.yml:
#
#   include:
#     - local: 'ci/gitlab-mr-review.yml'
#
# Or copy the job directly into your .gitlab-ci.yml
#

stages:
  - review

claude-mr-review:
  stage: review
  image: node:20-alpine

  # Only run on merge requests
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web" && $MR_IID
      when: manual

  variables:
    GIT_DEPTH: 0  # Full clone for accurate diffs

  before_script:
    - apk add --no-cache git curl jq
    - npm install -g @anthropic-ai/claude-code

  script:
    - |
      set -e

      # Get MR info
      MR_IID="${CI_MERGE_REQUEST_IID:-$MR_IID}"
      SOURCE_BRANCH="${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME:-$(git branch --show-current)}"
      TARGET_BRANCH="${CI_MERGE_REQUEST_TARGET_BRANCH_NAME:-main}"

      echo "Reviewing MR !$MR_IID: $SOURCE_BRANCH → $TARGET_BRANCH"

      # Fetch branches
      git fetch origin "$TARGET_BRANCH"
      git fetch origin "$SOURCE_BRANCH"

      # Get diff stats
      FILES=$(git diff "origin/$TARGET_BRANCH"..."origin/$SOURCE_BRANCH" --name-only | wc -l)
      ADDITIONS=$(git diff "origin/$TARGET_BRANCH"..."origin/$SOURCE_BRANCH" --numstat | awk '{sum += $1} END {print sum+0}')
      DELETIONS=$(git diff "origin/$TARGET_BRANCH"..."origin/$SOURCE_BRANCH" --numstat | awk '{sum += $2} END {print sum+0}')

      # Get commits
      COMMITS=$(git log "origin/$TARGET_BRANCH".."origin/$SOURCE_BRANCH" --oneline)

      # Get diff (limit size)
      DIFF=$(git diff "origin/$TARGET_BRANCH"..."origin/$SOURCE_BRANCH" | head -c 100000)

      # Build review prompt
      PROMPT="You are reviewing a merge request.

      Branch: $SOURCE_BRANCH → $TARGET_BRANCH
      Files changed: $FILES
      Lines: +$ADDITIONS / -$DELETIONS

      Commits:
      $COMMITS

      Provide a concise, actionable review formatted as clean markdown.

      Structure:
      ## Summary
      (2-3 sentences)

      ## Key Changes
      - Main changes as bullet points

      ## Review

      ### Issues Found
      (Be specific with file:line references)

      ### Suggestions
      (Specific improvements)

      ## Verdict
      🟢 Ready to merge | 🟡 Minor changes needed | 🔴 Needs work

      Diff:
      \`\`\`diff
      $DIFF
      \`\`\`"

      # Run Claude
      echo "$PROMPT" | claude --print > review.md 2>&1 || echo "Review generation failed" > review.md

      # Post comment to MR via GitLab API
      REVIEW_CONTENT=$(cat review.md)

      # Create comment body
      COMMENT_BODY=$(cat <<EOF
      # 🤖 Claude Review

      $REVIEW_CONTENT

      ---
      <sub>Generated by [Claude Code Starter](https://github.com/zbruhnke/claude-code-starter)</sub>
      EOF
      )

      # Check for existing bot comment
      EXISTING_COMMENT=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$MR_IID/notes" \
        | jq -r '.[] | select(.body | contains("<!-- claude-review -->")) | .id' | head -1)

      if [ -n "$EXISTING_COMMENT" ] && [ "$EXISTING_COMMENT" != "null" ]; then
        # Update existing comment
        curl -s --request PUT \
          --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --header "Content-Type: application/json" \
          --data "$(jq -n --arg body "<!-- claude-review -->$COMMENT_BODY" '{body: $body}')" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$MR_IID/notes/$EXISTING_COMMENT"
        echo "Updated existing review comment"
      else
        # Create new comment
        curl -s --request POST \
          --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
          --header "Content-Type: application/json" \
          --data "$(jq -n --arg body "<!-- claude-review -->$COMMENT_BODY" '{body: $body}')" \
          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/merge_requests/$MR_IID/notes"
        echo "Created new review comment"
      fi

  artifacts:
    paths:
      - review.md
    expire_in: 1 week
